# IF this is set to true, we look for the minecraft worldborder. 
# Set to true ONLY if you have a MINECRAFT worldborder set, not a plugin border.
# Keep in mind, the minecraft default world border is 29,999,999.
use-worldborder: false

# min blocks from spawn to.. spawn the player
min-spawn-distance: 200

# Max distance from spawn or look @ worldborder
# Options specified as:
# max-spawn-distance: 5000
max-distance: 1000

# Only if teleport-type: wild
# If true, it will be removed when they stop gliding or hit the ground.
give-elytra: true

# In seconds
command-cooldown: 300

# Seconds the player is immune from damage post-teleport.
immunity-seconds: 60
