# If this is set to true, we look for the minecraft worldborder. 
# Set to true ONLY if you have a MINECRAFT worldborder set, not a plugin border.
# Keep in mind, the minecraft default world border is 29,999,999.
#
# If this is set to false, the max-teleport-distance is used as the border ( minus 10% )
use-worldborder: true

# Max distance from spawn
# This is ignored if use-worldborder is true.
max-teleport-distance: 2500

# Matches against the whole biome string.
# Adding "ocean" will ensure players cannot land in *OCEAN* biomes.
# Make it empty to allow any.
blacklist-biomes:
- ocean

# Use particle effects on-teleport. Pointless for now.
# It works, but it's not fleshed out with any variability
use-effects: false

# Seconds before someone can run /wild again
command-cooldown: 30

# Seconds the player is immune from damage post-teleport.
immunity-seconds: 15
