# IF this is set to true, we look for the minecraft worldborder. 
# Set to true ONLY if you have a MINECRAFT worldborder set, not a plugin border.
# Keep in mind, the minecraft default world border is 29,999,999.
#
# If this is set to false, the max-teleport-distance is used as the border ( minus 10% )
use-worldborder: false

# min blocks from spawn to.. spawn the player
min-teleport-distance: 500

# Max distance from spawn or look @ worldborder
# Options specified as:
# max-spawn-distance: 5000
max-teleport-distance: 2500

# In seconds
command-cooldown: 300

# Seconds the player is immune from damage post-teleport.
immunity-seconds: 60
